### ISSUE TITLE
InvalidMimeTypeException for woff and ttf resources

### ISSUE THREAD

**Issue by jajimene** [sdl/dxa-web-application-java#101]
Hi,

We currently have some static resources we serve from the /system/assets folder of the webapp. All assets are working except for the .ttf and .woff files, that are not properly served and return this exception in the console:

`Invalid mime type "null": 'mimeType' must not be empty`

Debugging, I found out the error is coming from the `StaticContentInterceptor` class, where:

```
String mimeType = MimeUtils.getMimeType(contentResource);
res.getHeaders().setContentType(MediaType.parseMediaType(mimeType));
```
resolves `mimeType` to null, causing `MediaType.parseMediaType(mimeType)` to fail. This is due to the class `MimeUtils` not containing a key for `ttf` and `woff` in its `MIME_TYPES` map.

How can we workaround this issue to serve `woff`, `ttf` and other not included Mime types?

**Comment by bkoopman** [comment]
Looking at https://github.com/sdl/dxa-web-application-java/blob/develop/dxa-framework/dxa-common-api/src/main/java/com/sdl/webapp/common/util/MimeUtils.java#L19 it seems the only option is to add the missing MIME  types, although I wonder if we should consider using a third party library for this instead of maintaining a list ourselves.

**Comment by rpannekoek** [comment]
It seems this issue is actually a Question and another Issue (#109) has been created for the actual Issue in code.
