### ISSUE TITLE
Fielddata from keywords is not mapped correctly

### ISSUE THREAD

**Issue by martinhaggren** [sdl/dxa-web-application-java#4]
(This issue is reproducable in the example-webapp (see attached image). 

When using keywords, as for example in the "Social Network Pages"-component that is a part of the footer on the homepage of the example-webapp, the data from the keyword isn't mapped, giving null-values when mapped to the entities.

![example-webapp-social-sharing-icons](https://cloud.githubusercontent.com/assets/16350832/11897879/9f9c2876-a593-11e5-963f-8e1a6dcb4f96.JPG)

**Comment by bkoopman** [comment]
@martinhaggren I quickly checked on our development environments and it is not reproducible over there, I have to say that our currentl development environment is of course Web 8 and a DXA 1.3 version, so there are differences there. But is there any way you can provide us with some more information around this issue?

**Comment by Jasmeet0108** [comment]
This issue seems to be with KeywordFieldConverter where getFieldValues method is trying to fetch values from field.getKeywordValues() as list of keywords but in actual the value is coming in field.getTextValues() as List of String. 
This in-turn also have issue as previously it was giving "Description" field in older DXA version but in DXA1.2 it is giving "Value" field from CMS. We are not getting complete Keyword class fields.

Kindly suggest further.

**Comment by bkoopman** [comment]
best suggestion I can give is to use DXA 1.2 completely, which might mean you need to compare all the details or start with DXA 1.2 as a base and integrate your own changes in that. Since both the CM side and core code have changes over the pre releases, and there is no documented migration path between the two.

**Comment by jhorsman** [comment]
I had similar DXA JAVA keyword issues when using the DXA 1.2 web application, with a DXA JAVA development build on the Content Manager side. 

The root cause is a change in the JSON serialization of the Tridion page. This changed in DD4T 2.0 in this commit https://github.com/dd4t/dd4t-2-java/commit/e12ce21ec757678356d32f07233c4aba9e1a8e1e. DD4T 2.0 uses "KeywordValues" instead of "Keywords". The DXA JAVA development build  ships a version of DD4T which uses the older "Keywords" serialization.

So upgrade at least your DD4T TBB to DD4T 2.0, republish, and you should be fine.

Like @bkoopman said, it is better to update the CM side to DXA 1.2 completely. Apart from the DD4T TBBs some other suff changed as well, i.e. DD4T is not a separate module anymore but part of the DXA core.

**Comment by martinhaggren** [comment]
Thank you all. Updating the DD4T TBB's did the trick. I'm closing this issue.
