### ISSUE TITLE
Import dxa-bom not considering dxa-bom-2013sp1

### ISSUE THREAD

**Issue by tfinez** [sdl/dxa-web-application-java#57]
The pom.xml file in dxa-bom has libraries that are already in the pom of dxa-bom-2013, e.g. ehcache. As the pom of the project dxa-bom-2013 imports the pom of the dxa-bom project, we will have loaded in the same pom repeated libraries with different versions. I was checking the documentation and it's not up to date, due to the repo structure doesn't correspond with the one described [there](http://docs.sdl.com/LiveContent/content/en-US/SDL%20DXA-v5/GUID-184C4EB0-A8BF-4A10-9545-58F5F7662E38#url=/LiveContent/web/search.xql%3Fc%3Dt%26pub%3DSDL+DXA-v5%26lang%3Den-US%26action%3Dsearch%26query%3Ddxa%255C-bom%255C-2013sp1&sid=lcSearch.runSearch1472120386566&currentQuery=dxa%255C-bom%255C-2013sp1&currentScope=&eventType=lcContent.loadDocGUID-184C4EB0-A8BF-4A10-9545-58F5F7662E38&query=&scope=&filename=GUID-184C4EB0-A8BF-4A10-9545-58F5F7662E38.xml&docid=GUID-184C4EB0-A8BF-4A10-9545-58F5F7662E38&inner_id=&tid=&addHistory=true&resource=&toc=false). 

If there are common packages with same versions dxa-bom is needed as well as dxa-bom-web8 and dxa-bom-2013sp1 for specific libs.

**Comment by azarakovsky** [comment]
Hi @tfinez 

Indeed, the project structure has been changed again since 1.4: dxa-bom-web8 was removed and other boms were also aligned a bit. In the upcoming 1.6 you'll see dxa-bom (with common dependencies), dxa-bom-2013sp1 with 2013sp1-specific dependencies and also dxa-bom-modules with DXA modules.

The project structure should be definitely updated in docs.

Now, in order to work with default DXA, you need dxa-bom and dxa-bom-modules. **Additionally** you need dxa-bom-2013sp1 for 2013sp1. Also for 2013sp1 you need to set net.sf.ehcache:ehcache:2.8.2 in your webapp (Maven prefers webapp's closest dependencies). Look at profile 2013sp1: https://github.com/sdl/dxa-web-application-java/blob/master/dxa-webapp/pom.xml

**Comment by rpannekoek** [comment]
Reflected in DXA 1.6 docs.
