### ISSUE TITLE
Not possible to map multimedia link to a String property containing binary URL

### ISSUE THREAD

**Issue by willprice76** [sdl/dxa-web-application-java#99]
In the EntityModelDataConverter, if the target property is a string, the DXA puts the resolved URL of the linked Entity in the property. If this is a multimedia component, then the resolved URL is null, but what you really want is the Binary URL.

**Comment by rpannekoek** [comment]
Internal Issue ID (for tracking purposes): CRQ-12812

**Comment by rpannekoek** [comment]
Work-around is to map to a property of type `Link`, but indeed `String` should also work (consistently for regular and Multimedia Components).

**Comment by rpannekoek** [comment]
It turns out that this is "by design";  when mapping a Component Link filed to a property of type `String` or type `Link`, the value of the property will be the resolved URL of the _Page_ which contains the linked Component (if any).
This applies both to regular Components and Multimedia Components.
If you want to obtain the Binary URL for a Multimedia Component, you should map the (MM) Component Link field to an embedded Entity Model derived from {{MediaItem}}.
